# Generated by Django 4.1.2 on 2022-11-01 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tailwindapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='feature',
            field=models.ImageField(blank=True, null=True, upload_to='projects/images/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='projects/images/'),
        ),
    ]
