# Generated by Django 4.1.2 on 2022-11-01 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tailwindapp', '0002_alter_project_feature_alter_project_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='feature',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
