# Generated by Django 4.1.2 on 2022-10-30 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tailwindapp', '0003_alter_info_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='cv',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
