# Generated by Django 4.1.2 on 2022-10-30 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tailwindapp', '0004_info_cv'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('odoo', 'Odoo'), ('django', 'Django'), ('cybersecurity', 'CyberSecurity'), ('xml', 'XML'), ('python', 'Python')], default='odoo', max_length=25)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('body', models.TextField()),
                ('released', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tailwindapp.info')),
            ],
            options={
                'ordering': ['-released'],
            },
        ),
    ]
