# Generated by Django 4.1.2 on 2022-11-03 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tailwindapp', '0004_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyExp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=1000)),
                ('date', models.DateField(null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tailwindapp.companyexp')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tailwindapp.info')),
            ],
        ),
    ]
