# Generated by Django 4.1.2 on 2022-11-03 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tailwindapp', '0005_companyexp_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='title',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
