# Generated by Django 4.1.2 on 2022-11-07 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tailwindapp', '0006_experience_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='type',
        ),
        migrations.AddField(
            model_name='post',
            name='type',
            field=models.ManyToManyField(to='tailwindapp.category'),
        ),
    ]
