# Generated by Django 4.1.2 on 2022-11-07 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tailwindapp', '0007_remove_post_type_post_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='type',
        ),
    ]
