# Generated by Django 4.1.2 on 2022-11-07 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tailwindapp', '0008_remove_post_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
