# Generated by Django 4.1.2 on 2022-10-31 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tailwindapp', '0009_project_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='feature',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
