# Generated by Django 4.1.2 on 2022-11-07 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tailwindapp', '0010_post_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(max_length=255)),
                ('percent', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='info',
            name='skills',
            field=models.ManyToManyField(to='tailwindapp.skills'),
        ),
    ]
