# Generated by Django 4.1.2 on 2022-11-07 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tailwindapp', '0011_skills_info_skills'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='info',
            name='skills',
        ),
        migrations.AddField(
            model_name='info',
            name='skills',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='tailwindapp.skills'),
        ),
    ]
